const mongoose = require('mongoose')

const User = mongoose.model('FfUser', {
    namaTur: {
        type: String,
        require: true,
    },
    email: {
        type: String,
        require: true,
    },
    password: {
        type: String,
        require: true,
    },
    data: {
        tim1: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim2: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim3: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim4: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim5: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim6: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim7: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim8: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim9: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim10: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim11: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
        tim12: {
            namaTim: String,
            m1r: Number,
            m1k: Number,
            m2r: Number,
            m2k: Number,
            m3r: Number,
            m3k: Number,
            total: Number,
            rank: Number,
        },
    }
})

module.exports = User